#!/bin/sh
curl -X PUT "localhost:9200/_template/template_1?pretty" -H 'Content-Type: application/json' -d'
{
  "index_patterns": ["logstash*"],
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "properties": {
      "@timestamp": {
        "type": "date"
      },
      "tag": {
        "type": "keyword"
      },
      "host": {
        "type": "keyword"
      },
      "insert-id": {
        "type": "keyword"
      },
      "location": {
        "type": "geo_point"
      },
      "cost": {
        "type": "float"
      },
      "score": {
        "type": "float"
      },
      "category": {
        "type": "integer"
      }
    }
  }
}
'

