#!/bin/sh
curl -X PUT "localhost:9200/_template/template_1?pretty" -H 'Content-Type: application/json' -d'
{
  "index_patterns": ["app*"],
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "properties": {
      "date": {
        "type": "date"
      },
      "tag": {
        "type": "keyword"
      },
      "host": {
        "type": "keyword"
      },
      "insert-id": {
        "type": "keyword"
      },
      "location": {
        "type": "geo_point"
      },
      "cost": {
        "type": "double"
      },
      "score": {
        "type": "double"
      },
      "category": {
        "type": "integer"
      }
    }
  }
}
'

